[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.pdo_pgsql", "php82Extensions.mbstring", "php82Extensions.curl"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan migrate --force",
  "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
