[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.pdo_pgsql", "php82Extensions.mbstring", "php82Extensions.curl"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
