[phases.setup]
nixPkgs = ["php", "php82", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.pdo_mysql", "php82Extensions.pdo_pgsql"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
